<#
.SYNOPSIS
  Aggregate every topic file's "Interview-ready summary" + "Common pitfalls"
  sections into one cross-cutting revision document.

.DESCRIPTION
  Walks every *.md under mastery-guide/. For each file:
    - Extract the H2 section "Interview-ready summary" (heading + body).
    - Extract the H2 section "Common pitfalls" (heading + body).
    - Track the source file's H1 title + relative path.

  Output: mastery-guide/INTERVIEW_INDEX.md with sections grouped by chapter.
  Each entry has a backlink to the source file.

  Re-run any time after content changes.
#>

$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..\mastery-guide')
$indexPath = Join-Path $root 'INTERVIEW_INDEX.md'

# Per chapter -> array of entries (file title, rel path, summary, pitfalls)
$byChapter = [ordered]@{}

function Extract-Section {
    param([string]$Content, [string]$HeadingName)
    # Match: ## <HeadingName>\n<body>\n## ... (next H2 or H1 or end)
    $pattern = "(?ms)^##\s+$([regex]::Escape($HeadingName))\s*$\r?\n(.*?)(?=^#{1,2}\s|\z)"
    if ($Content -match $pattern) {
        return $matches[1].TrimEnd()
    }
    return $null
}

# Rewrite all relative links in a chunk of text so they resolve from the
# index's location (mastery-guide root) rather than from the source file.
function Rewrite-RelativeLinks {
    param(
        [string]$Text,
        [string]$SourceFileRel  # e.g. "02-api-development/04-api-security.md"
    )
    $sourceDir = Split-Path $SourceFileRel -Parent
    if ([string]::IsNullOrEmpty($sourceDir)) { return $Text }

    $linkPattern = '(?<!\!)\[(?<text>[^\]]+)\]\((?<url>[^)\s]+?)(?:\s+"[^"]*")?\)'
    return [regex]::Replace($Text, $linkPattern, {
        param($m)
        $linkText = $m.Groups['text'].Value
        $url = $m.Groups['url'].Value
        # Skip external + protocol + bare anchors
        if ($url -match '^(https?:|mailto:|tel:|//|#)') { return $m.Value }
        # Combine source dir with relative link, then normalize
        $combined = Join-Path $sourceDir $url
        $combined = $combined -replace '\\', '/'
        # Resolve any ../ segments
        $parts = New-Object System.Collections.Generic.List[string]
        foreach ($seg in $combined -split '/') {
            if ($seg -eq '..') {
                if ($parts.Count -gt 0) { $parts.RemoveAt($parts.Count - 1) }
            } elseif ($seg -ne '.' -and $seg -ne '') {
                $parts.Add($seg)
            }
        }
        $resolved = './' + ($parts -join '/')
        return "[$linkText]($resolved)"
    })
}

function Get-ChapterFolder {
    param([string]$RelPath)
    return ($RelPath -split '[\\/]')[0]
}

function Get-FileTitle {
    param([string]$Content)
    if ($Content -match '(?m)^#\s+(.+?)\s*$') { return $matches[1] }
    return '(untitled)'
}

# Friendly chapter title
function Get-ChapterTitle {
    param([string]$ChapterFolder)
    $readme = Join-Path $root "$ChapterFolder\README.md"
    if (Test-Path $readme) {
        $first = Get-Content $readme -TotalCount 1 -Encoding UTF8
        if ($first -match '^#\s+(.+?)\s*$') { return $matches[1] }
    }
    return $ChapterFolder
}

Get-ChildItem $root -Recurse -Filter *.md |
    Where-Object {
        $_.FullName -notmatch '\\_templates\\' -and
        $_.FullName -notmatch '\\_reports\\' -and
        $_.Name -ne 'README.md' -and
        $_.Name -ne 'INTERVIEW_INDEX.md'
    } |
    Sort-Object FullName |
    ForEach-Object {
        $file = $_.FullName
        $rel = $file.Substring($root.Path.Length + 1).Replace('\','/')
        $content = Get-Content $file -Raw -Encoding UTF8

        $summary = Extract-Section $content 'Interview-ready summary'
        $pitfalls = Extract-Section $content 'Common pitfalls'

        if (-not $summary -and -not $pitfalls) { return }

        # Rewrite relative links so they resolve from the index location
        if ($summary)  { $summary = Rewrite-RelativeLinks $summary $rel }
        if ($pitfalls) { $pitfalls = Rewrite-RelativeLinks $pitfalls $rel }

        $chapter = Get-ChapterFolder $rel
        $title = Get-FileTitle $content

        if (-not $byChapter.Contains($chapter)) {
            $byChapter[$chapter] = @()
        }
        $byChapter[$chapter] += [pscustomobject]@{
            Title = $title
            RelPath = $rel
            Summary = $summary
            Pitfalls = $pitfalls
        }
    }

# Build the report
$emdash = [string]::new([char]0x2014)
$report = New-Object System.Text.StringBuilder

[void]$report.AppendLine("# Interview Drill Index")
[void]$report.AppendLine("")
[void]$report.AppendLine("> Auto-generated by ``scripts/build-interview-index.ps1``. Do not edit by hand.")
[void]$report.AppendLine(">")
[void]$report.AppendLine("> Aggregates every topic file's **Interview-ready summary** and **Common pitfalls** sections into one revision document. Use it for spaced-repetition style review the night before an interview.")
[void]$report.AppendLine("")

# TOC
[void]$report.AppendLine("## Contents")
[void]$report.AppendLine("")
foreach ($entry in $byChapter.GetEnumerator()) {
    $chapTitle = Get-ChapterTitle $entry.Key
    $chapAnchor = ($chapTitle.ToLowerInvariant() -replace '[^\p{L}\p{Nd}\s\-_]', '' -replace '\s', '-').Trim('-')
    [void]$report.AppendLine("- [$chapTitle](#$chapAnchor) ($($entry.Value.Count) topics)")
}
[void]$report.AppendLine("")
[void]$report.AppendLine("---")
[void]$report.AppendLine("")

# Excerpts are lifted verbatim out of a topic file and pasted into this index,
# which sits at the mastery-guide root. A same-page `](#some-heading)` link is
# therefore wrong here -- the index has no such heading -- so point it back at
# the heading in the source file.
#
# Only same-page fragments are rewritten. File links inside excerpts are already
# written to resolve from the index and must be left alone; rebasing them onto
# the topic's directory double-prefixes them.
function Resolve-ExcerptLinks {
    param([string]$Text, [string]$RelPath)
    if (-not $Text) { return $Text }
    return [regex]::Replace($Text, '\]\(#([^)]+)\)', { "](${RelPath}#$($args[0].Groups[1].Value))" })
}

# Per-chapter sections
foreach ($entry in $byChapter.GetEnumerator()) {
    $chapTitle = Get-ChapterTitle $entry.Key
    [void]$report.AppendLine("## $chapTitle")
    [void]$report.AppendLine("")

    foreach ($topic in $entry.Value) {
        $line = "### {0}" -f $topic.Title
        [void]$report.AppendLine($line)
        $sourceLine = "_Source: [{0}]({0})_" -f $topic.RelPath
        [void]$report.AppendLine($sourceLine)
        [void]$report.AppendLine("")

        if ($topic.Summary) {
            [void]$report.AppendLine("**Interview-ready summary**")
            [void]$report.AppendLine("")
            [void]$report.AppendLine((Resolve-ExcerptLinks $topic.Summary $topic.RelPath))
            [void]$report.AppendLine("")
        }
        if ($topic.Pitfalls) {
            [void]$report.AppendLine("**Common pitfalls**")
            [void]$report.AppendLine("")
            [void]$report.AppendLine((Resolve-ExcerptLinks $topic.Pitfalls $topic.RelPath))
            [void]$report.AppendLine("")
        }
    }

    [void]$report.AppendLine("---")
    [void]$report.AppendLine("")
}

[System.IO.File]::WriteAllText($indexPath, $report.ToString(), (New-Object System.Text.UTF8Encoding($false)))

$totalTopics = ($byChapter.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum
Write-Host "Index written: $indexPath"
Write-Host ""
Write-Host "Chapters: $($byChapter.Count)"
Write-Host "Topics with revision content: $totalTopics"
