<#
.SYNOPSIS
  Detect content duplication across mastery-guide topic files.

.DESCRIPTION
  Three reports:
    1. Heading collisions  — same normalized heading appears in 2+ files.
    2. Duplicate code blocks — identical fenced blocks (>= 5 lines) appear in 2+ files.
    3. High section-overlap pairs — pairs of files where >30% of their
       H2/H3 headings overlap (suggests significant content duplication).

  Output: mastery-guide/_reports/duplications.md (overwritten each run).

  Light-tier detection only. False positives (e.g. shared "Common pitfalls"
  section heading) are expected and easy to skim past. The report is a
  punch list for human review, not an auto-fixer.
#>

$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..\mastery-guide')
$reportsDir = Join-Path $root '_reports'
if (-not (Test-Path $reportsDir)) {
    New-Item -ItemType Directory -Path $reportsDir -Force | Out-Null
}
$reportPath = Join-Path $reportsDir 'duplications.md'

# Boilerplate headings to ignore (these appear in every file by design)
$boilerplateHeadings = @(
    'why it matters', 'core concepts', 'code & diagrams', 'common pitfalls',
    'interview-ready summary', 'cross-references', 'sources', 'contents'
)

function Norm-Heading {
    param([string]$h)
    $s = $h.ToLowerInvariant()
    $s = $s -replace '^#+\s*', ''
    $s = $s -replace '[^\p{L}\p{Nd}\s\-_]', ''
    $s = ($s -replace '\s+', ' ').Trim()
    return $s
}

# Per-file: array of H2/H3 normalized headings
$fileHeadings = @{}
# Global: normalized heading -> list of files
$headingMap = @{}
# Global: code-block-hash -> list of (file, lines)
$codeBlockMap = @{}

Get-ChildItem $root -Recurse -Filter *.md |
    Where-Object {
        $_.FullName -notmatch '\\_templates\\' -and
        $_.FullName -notmatch '\\_reports\\'
    } |
    ForEach-Object {
        $file = $_.FullName
        $rel = $file.Substring($root.Path.Length + 1).Replace('\','/')
        $lines = Get-Content $file -Encoding UTF8

        $headingsHere = @()
        $inFence = $false
        $fenceLang = ''
        $fenceLines = @()
        $fenceStartLine = 0

        for ($i = 0; $i -lt $lines.Count; $i++) {
            $line = $lines[$i]
            if ($line -match '^```(\S*)') {
                if (-not $inFence) {
                    $inFence = $true
                    $fenceLang = $matches[1]
                    $fenceLines = @()
                    $fenceStartLine = $i + 1
                } else {
                    # Closing fence
                    $inFence = $false
                    if ($fenceLines.Count -ge 5) {
                        $body = ($fenceLines -join "`n").Trim()
                        # Normalize: strip leading/trailing whitespace per line
                        $hash = [System.BitConverter]::ToString(
                            [System.Security.Cryptography.SHA1]::Create().ComputeHash(
                                [System.Text.Encoding]::UTF8.GetBytes($body))
                        ).Replace('-', '')
                        if (-not $codeBlockMap.ContainsKey($hash)) {
                            $codeBlockMap[$hash] = @()
                        }
                        $codeBlockMap[$hash] += [pscustomobject]@{
                            File = $rel
                            Line = $fenceStartLine
                            LineCount = $fenceLines.Count
                            Lang = $fenceLang
                            Preview = ($fenceLines | Select-Object -First 1)
                        }
                    }
                }
                continue
            }

            if ($inFence) {
                $fenceLines += $line
                continue
            }

            # Headings (H2/H3 only — skip H1 file titles, skip H4+ noise)
            if ($line -match '^(##|###)\s+(.+?)\s*$') {
                $norm = Norm-Heading $matches[2]
                if ([string]::IsNullOrWhiteSpace($norm)) { continue }
                if ($boilerplateHeadings -contains $norm) { continue }
                $headingsHere += $norm
                if (-not $headingMap.ContainsKey($norm)) {
                    $headingMap[$norm] = @()
                }
                $headingMap[$norm] += [pscustomobject]@{
                    File = $rel
                    Line = $i + 1
                    Original = $matches[2]
                }
            }
        }

        $fileHeadings[$rel] = $headingsHere
    }

# --- Build the report ---

$now = (Get-Date).ToString('yyyy-MM-dd HH:mm')
$report = New-Object System.Text.StringBuilder
[void]$report.AppendLine("# Duplication Report")
[void]$report.AppendLine("")
[void]$report.AppendLine("> Auto-generated by ``scripts/find-duplicates.ps1`` at $now.")
[void]$report.AppendLine(">")
[void]$report.AppendLine("> Light-tier detection: heading collisions, duplicate code blocks, high section-overlap pairs.")
[void]$report.AppendLine("> Boilerplate headings (Why it matters, Common pitfalls, etc.) are excluded by design.")
[void]$report.AppendLine("")
[void]$report.AppendLine("---")
[void]$report.AppendLine("")

# 1. Heading collisions
$collisions = $headingMap.GetEnumerator() | Where-Object { $_.Value.Count -ge 2 } | Sort-Object { -$_.Value.Count }, Key
[void]$report.AppendLine("## 1. Heading collisions ($($collisions.Count) groups)")
[void]$report.AppendLine("")
if ($collisions.Count -eq 0) {
    [void]$report.AppendLine("_No collisions found._")
} else {
    [void]$report.AppendLine("Headings that appear in 2+ files. Most are intentional (parallel structure); flag any unexpected matches.")
    [void]$report.AppendLine("")
    $emdash = [string]::new([char]0x2014)
    foreach ($entry in $collisions) {
        [void]$report.AppendLine("### ``$($entry.Key)`` ($($entry.Value.Count) files)")
        foreach ($occurrence in $entry.Value) {
            $line = "- [{0}:{1}]({2}#L{1}) {3} {4}" -f $occurrence.File, $occurrence.Line, [uri]::EscapeUriString($occurrence.File), $emdash, $occurrence.Original
            [void]$report.AppendLine($line)
        }
        [void]$report.AppendLine("")
    }
}
[void]$report.AppendLine("---")
[void]$report.AppendLine("")

# 2. Duplicate code blocks
$dupCode = $codeBlockMap.GetEnumerator() | Where-Object { $_.Value.Count -ge 2 } | Sort-Object { -$_.Value[0].LineCount }
[void]$report.AppendLine("## 2. Duplicate code blocks ($($dupCode.Count) groups)")
[void]$report.AppendLine("")
if ($dupCode.Count -eq 0) {
    [void]$report.AppendLine("_No duplicate code blocks (>= 5 lines) found._")
} else {
    [void]$report.AppendLine("Identical fenced code blocks (>= 5 lines) appearing in 2+ files. Likely candidates for canonical-source-and-link consolidation.")
    [void]$report.AppendLine("")
    foreach ($entry in $dupCode) {
        $first = $entry.Value[0]
        [void]$report.AppendLine("### $($first.LineCount)-line $($first.Lang) block ($($entry.Value.Count) copies)")
        [void]$report.AppendLine("Preview: ``$($first.Preview)``")
        foreach ($occ in $entry.Value) {
            [void]$report.AppendLine("- $($occ.File):$($occ.Line)")
        }
        [void]$report.AppendLine("")
    }
}
[void]$report.AppendLine("---")
[void]$report.AppendLine("")

# 3. High section-overlap pairs
[void]$report.AppendLine("## 3. High section-overlap pairs (Jaccard >= 0.30)")
[void]$report.AppendLine("")

$overlapPairs = New-Object System.Collections.Generic.List[object]
$files = @($fileHeadings.Keys | Sort-Object)
for ($i = 0; $i -lt $files.Count; $i++) {
    $a = $files[$i]
    $setA = $fileHeadings[$a]
    if ($setA.Count -lt 3) { continue }  # too few headings to be meaningful
    for ($j = $i + 1; $j -lt $files.Count; $j++) {
        $b = $files[$j]
        $setB = $fileHeadings[$b]
        if ($setB.Count -lt 3) { continue }

        $intersect = ($setA | Where-Object { $setB -contains $_ }).Count
        if ($intersect -eq 0) { continue }
        $union = ($setA + $setB | Select-Object -Unique).Count
        $jaccard = $intersect / $union
        if ($jaccard -ge 0.30) {
            $overlapPairs.Add([pscustomobject]@{
                FileA = $a
                FileB = $b
                ASize = $setA.Count
                BSize = $setB.Count
                Shared = $intersect
                Jaccard = [math]::Round($jaccard, 2)
            })
        }
    }
}

if ($overlapPairs.Count -eq 0) {
    [void]$report.AppendLine("_No file pairs above the 30% threshold._")
} else {
    [void]$report.AppendLine("Pairs of files where 30%+ of H2/H3 headings overlap. Strong candidates for consolidation review.")
    [void]$report.AppendLine("")
    [void]$report.AppendLine("| Jaccard | Shared | A (size) | B (size) |")
    [void]$report.AppendLine("|---:|---:|---|---|")
    foreach ($p in ($overlapPairs | Sort-Object Jaccard -Descending)) {
        [void]$report.AppendLine("| $($p.Jaccard) | $($p.Shared) | $($p.FileA) ($($p.ASize)) | $($p.FileB) ($($p.BSize)) |")
    }
}

[void]$report.AppendLine("")
[void]$report.AppendLine("---")
[void]$report.AppendLine("")
[void]$report.AppendLine("**Files analyzed:** $($fileHeadings.Count) topic files.")

[System.IO.File]::WriteAllText($reportPath, $report.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Report written: $reportPath"
Write-Host ""
Write-Host "Heading collisions: $($collisions.Count)"
Write-Host "Duplicate code blocks: $($dupCode.Count)"
Write-Host "High-overlap pairs: $($overlapPairs.Count)"
